In [2]:
import numpy as np

In [2]:
print("Hello")

Hello


In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
arr = np.array([1,3,4,5])
arr

array([1, 3, 4, 5])

In [17]:
l = np.array([[1,2,4,5],[6,7,8,9],[2,5,6,7]])
l

array([[1, 2, 4, 5],
       [6, 7, 8, 9],
       [2, 5, 6, 7]])

In [6]:
np.array(l)

array([[1, 2, 4, 5],
       [6, 7, 8, 9],
       [2, 5, 6, 7]])

In [9]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [10]:
np.random.randint(10,20,10)

array([18, 10, 16, 11, 13, 11, 15, 13, 14, 19], dtype=int32)

In [11]:
np.sum(l, axis=1)

array([12, 30, 20])

In [12]:
np.sum(l,axis=0)

array([ 9, 14, 18, 21])

In [18]:
l.mean()

np.float64(5.166666666666667)

In [19]:
l.shape

(3, 4)

In [20]:
l.min()

np.int64(1)

In [21]:
l.max()

np.int64(9)

In [23]:
l.sum()

np.int64(62)

In [24]:
l.std()

np.float64(2.4094720491334933)

In [25]:
l.argmax()

np.int64(7)

In [28]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [32]:
arr = arr.reshape(5,6)

In [33]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])