In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
b  = a
b

array([1, 2, 3, 4, 5])

In [5]:
b[0] = 22

In [6]:
b

array([22,  2,  3,  4,  5])

In [7]:
a

array([22,  2,  3,  4,  5])

In [10]:
b = a.copy()
b

array([22,  2,  3,  4,  5])

In [11]:
b[4] = 0

In [12]:
b

array([22,  2,  3,  4,  0])

In [13]:
a

array([22,  2,  3,  4,  5])

In [ ]:
# Matrix operation

In [16]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])


In [17]:
A

array([[1, 2],
       [3, 4]])

In [18]:
B

array([[5, 6],
       [7, 8]])

In [19]:
A @ B

array([[19, 22],
       [43, 50]])

In [20]:
A

array([[1, 2],
       [3, 4]])

In [21]:
A.T

array([[1, 3],
       [2, 4]])

In [22]:
B.T

array([[5, 7],
       [6, 8]])

In [23]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8,])

In [25]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [29]:
f = np.hsplit(c,4)


[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [30]:
f

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [31]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]