In [ ]:
# Indexing

In [2]:
import numpy as np

In [3]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
arr[5:9]  

array([16, 17, 18, 19])

In [ ]:
# numpy indexing and slicing the matrix

In [8]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [11]:
arr[0,4]

np.int64(5)

In [25]:
arr[3:,2:4]

array([[18, 19],
       [23, 24],
       [28, 29]])

In [26]:
slice = arr[2:5,1:3]
slice

array([[12, 13],
       [17, 18],
       [22, 23]])

In [ ]:
# Bool indexing

In [31]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [32]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [33]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])