In [1]:
import numpy as np

Exercise 1: Create a 1D NumPy array of numbers from 0 to 9

In [46]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Exercise 2: Convert 1D array to 2D

In [47]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [48]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

Exercise 3: Print Array Attributes

In [49]:
my_array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print("The shape of my array is: ",np.shape(my_array))
print("The number of dimensions is: ",np.ndim(my_array))
print("The size of each element in bytes is: ", my_array.itemsize)

The shape of my array is:  (4, 2)
The number of dimensions is:  2
The size of each element in bytes is:  8


Exercise 4: Create a 3×3 NumPy array of all True

In [50]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Exercise 5: Extract the documentation of NumPy’s arange() function

In [51]:
np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The inter

Exercise 6: Create a 1D array filled with zeros and another filled with ones

In [52]:
print("Zeros: ", np.zeros(5))
print("Ones: ",np.ones(5))

Zeros:  [0. 0. 0. 0. 0.]
Ones:  [1. 1. 1. 1. 1.]


Exercise 7: Create a 1D array of 10 evenly spaced values between 5 and 50

In [53]:
np.linspace(5,50,10)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

Exercise 8: Convert a Python list into a NumPy array

In [54]:
py_list = [1, 2, 3, 4, 5]
np.array(py_list)

array([1, 2, 3, 4, 5])

Exercise 9: Find the memory size of a NumPy array of numbers from 0 to 9

In [55]:
a = np.arange(10)
print("Array: ",a)
print("Memory size in bytes: ", a.nbytes)

Array:  [0 1 2 3 4 5 6 7 8 9]
Memory size in bytes:  80


Exercise 10: Reverse a 1D NumPy array

In [59]:
np.arange(10)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Exercise 11: Create a 3×3 identity matrix

In [65]:
# np.arange(9).reshape(3,3)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Exercise 12: Create a 4×4 array and extract its first row and last column

In [108]:
ex = np.arange(1,17).reshape(4,4)
print("First Row: ", ex[0])
print("Last Column: ", ex[:,-1])

First Row:  [1 2 3 4]
Last Column:  [ 4  8 12 16]


Exercise 13: Extract Odd Rows and Even Columns

In [114]:
sampleArray = np.array([
    [3, 6, 9, 12], 
    [15, 18, 21, 24], 
    [27, 30, 33, 36], 
    [39, 42, 45, 48], 
    [51, 54, 57, 60]
])

mewArray = sampleArray[1::2,::2]
newArray


array([[15, 21],
       [39, 45]])

In [115]:
sampleArray

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60]])